"""Generate tab:db_comparison (MARINA-DB vs SPECTRE-DB, main), the supplementary MARINA-DB-PRIVATE vs MARINA-DB
table, and the development-dataset table (MARINA-DB-PARTIAL vs MARINA-DB-PRIVATE vs MARINA-DB) from the shipped
dataset indexes.

MARINA-DB         = $DATASETS_ROOT/MARINA-DB-OPEN (CH-NMR-NP-first build, zip sha256 2780459f...)
MARINA-DB-PRIVATE = $DATASETS_ROOT/MARINA-DB
MARINA-DB-PARTIAL = $DATASETS_ROOT/MARINA1 (no negative-mode MS/MS: that count is 0)
Counts = molecules with the has_* flag; experimental = NMR source 'chnmr' in nmr_sources.parquet.
SPECTRE-DB column is carried over from the previous table (external dataset, no local artifact).

Run (MARINA repo root):  DATASETS_ROOT=~/Workspace/Datasets pixi run python paper/db_comparison/gen_db_comparison.py
"""
import os
import pickle

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
DATASETS = os.environ.get("DATASETS_ROOT", os.path.expanduser("~/Workspace/Datasets"))

SPECTRE_DB = {"train": 173422, "val": 4056, "test": 4056, "has_hsqc": 117806, "has_c_nmr": 111521,
              "has_h_nmr": 101486, "has_mass_spec": 0, "has_mass_spec_neg": 0, "total": 181534,
              "retrieval": 526163}
NA = "{\\na}"
# SPECTRE-DB has experimental spectra but the paper does not give their counts; the * points to the caption note.
SPECTRE_DB.update({k: NA + "*" for k in ["exp_hsqc", "exp_c_nmr", "exp_h_nmr"]})


def stats(root, sources=False):
    idx = pickle.load(open(os.path.join(root, "index.pkl"), "rb"))
    df = pd.DataFrame(list(idx.values()))
    s = df.split.value_counts().to_dict()
    s.update({k: int(df[k].sum()) if k in df else 0
              for k in ["has_hsqc", "has_c_nmr", "has_h_nmr", "has_mass_spec", "has_mass_spec_neg"]})
    s["total"] = len(df)
    s["retrieval"] = len(pickle.load(open(os.path.join(root, "retrieval.pkl"), "rb")))
    if sources:
        src = pd.read_parquet(os.path.join(root, "nmr_sources.parquet"))
        for m in ["hsqc", "c_nmr", "h_nmr"]:
            s[f"exp_{m}"] = int((src[m] == "chnmr").sum())
    return s


COUNT_ROWS = [("Training Size", "train"), ("Validation Size", "val"), ("Test Size", "test"), None,
              ("HSQC Count", "has_hsqc"), ("$^{13}$C Count", "has_c_nmr"), ("$^{1}$H Count", "has_h_nmr"),
              ("MS/MS (+)", "has_mass_spec"), ("MS/MS ($-$)", "has_mass_spec_neg"), None,
              ("Total Size", "total"), ("Retrieval Set Size", "retrieval")]
EXP_AFTER = {"has_hsqc": "exp_hsqc", "has_c_nmr": "exp_c_nmr", "has_h_nmr": "exp_h_nmr"}


def table(cols, rows, header):
    w = max(len(r[0]) for r in rows if r) + 2
    out = [f"% Generated by gen_db_comparison.py — do not edit by hand.",
           "\\begingroup", "\\color{cInk}", "\\setlength{\\tabcolsep}{8pt}",
           "\\renewcommand{\\arraystretch}{1.15}",
           "\\begin{tabular}{@{}l" + " S[table-format=6.0]" * len(cols) + "@{}}", "  \\toprule",
           "  " + " " * w + "& " + " & ".join(f"{{\\hd{{{h}}}}}" for h in header) + " \\\\", "  \\midrule"]
    for r in rows:
        if r is None:
            out.append("  \\midrule")
            continue
        label, key = r
        out.append(f"  {label:<{w}}& " + " & ".join(str(c.get(key, NA)) for c in cols) + " \\\\")
    out += ["  \\bottomrule", "\\end{tabular}", "\\endgroup", ""]
    return "\n".join(out)


def main():
    new = stats(os.path.join(DATASETS, "MARINA-DB-OPEN"), sources=True)
    priv = stats(os.path.join(DATASETS, "MARINA-DB"))
    partial = stats(os.path.join(DATASETS, "MARINA1"))
    main_rows = []
    for r in COUNT_ROWS:
        main_rows.append(r)
        if r and r[1] in EXP_AFTER:
            main_rows.append(("\\quad experimental", EXP_AFTER[r[1]]))
    with open(os.path.join(HERE, "db_comparison.tex"), "w") as f:
        f.write(table([new, SPECTRE_DB], main_rows, ["MARINA-DB", "SPECTRE-DB"]))
    with open(os.path.join(HERE, "db_comparison_private.tex"), "w") as f:
        f.write(table([priv, new], COUNT_ROWS, ["MARINA-DB-PRIVATE", "MARINA-DB"]))
    with open(os.path.join(HERE, "db_comparison_dev.tex"), "w") as f:
        f.write(table([partial, priv, new], COUNT_ROWS, ["MARINA-DB-PARTIAL", "MARINA-DB-PRIVATE", "MARINA-DB"]))
    print("MARINA-DB-PARTIAL", partial)
    print("MARINA-DB", new)
    print("MARINA-DB-PRIVATE", priv)


if __name__ == "__main__":
    main()
